import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";
import { compositionKnobs, materialKnobs, materialKnobTarget, materialNames, materialTitles } from "./customization";

export const chromishTargets = {
  background: "appearance.background",
  backgroundImage: "media.backgroundImage",
  bevel: "geometry.bevel",
  depth: "geometry.depth",
  detail: "svg.detail",
  direction: "motion.direction",
  imageFormat: "export.image.format",
  imageResolution: "export.image.resolution",
  includeBackground: "export.includeBackground",
  orbit: "view.orbit",
  material: "material.type",
  primaryColor: "material.primaryColor",
  secondaryColor: "material.secondaryColor",
  reflectionContrast: "chrome.reflectionContrast",
  roughness: "chrome.roughness",
  source: "media.svgSource",
  startAngle: "motion.startAngle",
  studioRotation: "chrome.studioRotation",
  videoFormat: "export.video.format",
  videoResolution: "export.video.resolution",
} as const;

const always = { mode: "always" as const };

export const chromishControlSections = [
  {
    controls: {
      source: {
        accept: ".svg,image/svg+xml",
        applicability: always,
        assetKind: "file",
        defaultValue: null,
        description: "One SVG, up to 5 MB and 10,000 elements.",
        hardMaxItems: 1,
        label: "Source",
        multiple: false,
        orderRole: "input",
        performanceReason:
          "The uploader owns responsive admission feedback; source complexity is modeled separately as an external workload dimension.",
        performanceRole: "responsiveness",
        target: chromishTargets.source,
        type: "fileDrop",
      },
      detail: {
        applicability: always,
        defaultValue: "fine",
        description: "Fine traces at 1536 px with 24 curve subdivisions; Balanced uses 768 px and 12.",
        label: "Detail",
        options: [
          { label: "Fine", value: "fine" },
          { label: "Balanced", value: "balanced" },
        ],
        orderRole: "detail",
        performanceReason:
          "Detail changes the trace edge, curve subdivisions, and resulting mesh workload.",
        performanceRole: "workload",
        target: chromishTargets.detail,
        type: "segmented",
      },
    },
    id: "svg",
    layout: "standalone",
    title: "SVG",
  },
  {
    controls: {
      depth: {
        applicability: always,
        defaultValue: 0.24,
        description: "Extrudes the silhouette symmetrically around its center plane.",
        label: "Depth",
        max: 0.6,
        min: 0.04,
        orderRole: "spatial",
        performanceReason:
          "Depth rebuilds fixed-topology geometry only when its value changes.",
        performanceRole: "responsiveness",
        sliderValueKind: "continuous",
        step: 0.01,
        target: chromishTargets.depth,
        type: "slider",
      },
      bevel: {
        applicability: always,
        defaultValue: 0.04,
        description: "Rounds front and rear edges to catch studio reflections.",
        label: "Bevel",
        max: 0.12,
        min: 0,
        orderRole: "spatial",
        performanceReason:
          "Bevel rebuilds geometry at an explicit commit boundary; it does not run per frame.",
        performanceRole: "responsiveness",
        sliderValueKind: "continuous",
        step: 0.005,
        target: chromishTargets.bevel,
        type: "slider",
      },
      orientation: {
        applicability: always,
        defaultValue: { position: [0.15, 0.1, 4.5], up: [0, 1, 0] },
        keyframeable: false,
        label: false,
        performanceReason:
          "Orbit interaction updates camera uniforms without rebuilding source geometry.",
        performanceRole: "responsiveness",
        target: chromishTargets.orbit,
        type: "orientationGizmo",
      },
    },
    id: "geometry",
    title: "Geometry",
  },
  {
    controls: {
      material: {
        applicability: always,
        defaultValue: "chrome",
        description: "Switch between refractive, glossy, emissive, and soft sculpted finishes.",
        label: "Finish",
        options: [
          { label: "Chrome", value: "chrome" },
          { label: "Diamond", value: "diamond" },
          { label: "Shiny plastic", value: "plastic" },
          { label: "Glass", value: "glass" },
          { label: "Fire", value: "fire" },
          { label: "Playdough", value: "playdough" },
        ],
        orderRole: "mode",
        performanceReason: "Material choice selects one branch in the retained fragment shader.",
        performanceRole: "responsiveness",
        target: chromishTargets.material,
        type: "select",
      },
      primaryColor: {
        applicability: { all: [{ oneOf: ["chrome", "plastic", "fire", "playdough"], target: chromishTargets.material }], mode: "conditional" },
        defaultValue: "#E6ECEF",
        label: "Primary",
        orderRole: "color",
        semanticGroup: "material-colors",
        performanceReason: "Primary color updates one material uniform.",
        performanceRole: "responsiveness",
        target: chromishTargets.primaryColor,
        type: "color",
      },
      secondaryColor: {
        applicability: { all: [{ oneOf: ["plastic", "fire"], target: chromishTargets.material }], mode: "conditional" },
        defaultValue: "#FFD429",
        label: "Accent",
        orderRole: "color",
        semanticGroup: "material-colors",
        performanceReason: "Accent color updates the plastic highlight or fire core uniform.",
        performanceRole: "responsiveness",
        target: chromishTargets.secondaryColor,
        type: "color",
      },
      roughness: {
        applicability: { all: [{ oneOf: ["chrome", "plastic", "playdough"], target: chromishTargets.material }], mode: "conditional" },
        defaultValue: 0.12,
        label: "Roughness",
        max: 0.45,
        min: 0.03,
        orderRole: "strength",
        performanceReason: "Roughness updates one material uniform.",
        performanceRole: "responsiveness",
        sliderValueKind: "continuous",
        step: 0.01,
        target: chromishTargets.roughness,
        type: "slider",
      },
      reflectionContrast: {
        applicability: { all: [{ oneOf: ["chrome", "diamond", "glass"], target: chromishTargets.material }], mode: "conditional" },
        defaultValue: 1.25,
        label: "Reflection contrast",
        max: 2,
        min: 0.5,
        orderRole: "strength",
        performanceReason: "Reflection contrast updates one material uniform.",
        performanceRole: "responsiveness",
        sliderValueKind: "continuous",
        step: 0.05,
        target: chromishTargets.reflectionContrast,
        type: "slider",
      },
      studioRotation: {
        applicability: { all: [{ oneOf: ["chrome", "diamond", "glass"], target: chromishTargets.material }], mode: "conditional" },
        defaultValue: 18,
        label: "Studio rotation",
        max: 360,
        min: 0,
        orderRole: "spatial",
        performanceReason: "Studio rotation moves procedural reflection bands in the shader.",
        performanceRole: "responsiveness",
        sliderValueKind: "continuous",
        step: 1,
        target: chromishTargets.studioRotation,
        type: "slider",
        unit: "°",
      },
      exposure: {
        applicability: always,
        defaultValue: 1,
        label: "Exposure",
        max: 2,
        min: 0.5,
        orderRole: "strength",
        performanceReason: "Exposure updates the tone-map uniform only.",
        performanceRole: "responsiveness",
        sliderValueKind: "continuous",
        step: 0.05,
        target: "chrome.exposure",
        type: "slider",
      },
    },
    id: "material",
    title: "Material",
  },
  ...materialNames.map((material) => ({
    id: `material-${material}`,
    title: materialTitles[material],
    controls: Object.fromEntries(materialKnobs[material].map((item) => [item.key, {
      ...item, type: "slider" as const, target: materialKnobTarget(material, item.key),
      applicability: { mode: "conditional" as const, all: [{ target: chromishTargets.material, oneOf: [material] }] },
      performanceRole: "responsiveness" as const,
      performanceReason: "Updates retained material uniforms; source mesh and pass count stay unchanged.",
      sliderValueKind: "continuous" as const,
    }])),
  })),
  {
    id: "composition", title: "Composition",
    controls: Object.fromEntries(compositionKnobs.map((item) => [item.key, {
      ...item, type: "slider" as const, target: `composition.${item.key}`, applicability: always,
      performanceRole: "responsiveness" as const, performanceReason: "Updates transform or grading uniforms without rebuilding geometry.",
      sliderValueKind: "continuous" as const,
    }])),
  },
  {
    controls: {
      direction: {
        applicability: always,
        defaultValue: "clockwise",
        label: "Direction",
        options: [
          { label: "Clockwise", value: "clockwise" },
          { label: "Counterclockwise", value: "counterclockwise" },
        ],
        orderRole: "mode",
        performanceReason: "Direction changes the sign of the timeline angle uniform.",
        performanceRole: "responsiveness",
        target: chromishTargets.direction,
        type: "select",
      },
      startAngle: {
        applicability: always,
        defaultValue: -65,
        label: "Start angle",
        max: 180,
        min: -180,
        orderRole: "spatial",
        performanceReason: "Start angle updates the model transform uniform.",
        performanceRole: "responsiveness",
        sliderValueKind: "continuous",
        step: 1,
        target: chromishTargets.startAngle,
        type: "slider",
        unit: "°",
      },
    },
    id: "motion",
    title: "Motion",
  },
  {
    controls: {
      backgroundImage: {
        accept: "image/png,image/jpeg,image/webp",
        applicability: always,
        assetKind: "image",
        defaultValue: null,
        description: "Use a photo behind the object to inspect transparency, reflections, and refraction.",
        hardMaxItems: 1,
        label: false,
        multiple: false,
        orderRole: "input",
        performanceReason: "Image replacement decodes and uploads one bounded texture outside the frame loop.",
        performanceRole: "responsiveness",
        target: chromishTargets.backgroundImage,
        type: "fileDrop",
      },
    },
    id: "environment-image",
    title: "Environment Image",
  },
  {
    controls: {
      includeBackground: {
        applicability: always,
        defaultValue: true,
        description: "Include the canvas background in image and video output.",
        label: "Include",
        orderRole: "primary",
        performanceReason: "Background visibility changes a tone-map uniform.",
        performanceRole: "responsiveness",
        target: chromishTargets.includeBackground,
        type: "switch",
      },
      background: {
        applicability: always,
        defaultValue: "#F7F7F5",
        label: false,
        orderRole: "color",
        performanceReason: "Background color changes a tone-map uniform.",
        performanceRole: "responsiveness",
        target: chromishTargets.background,
        type: "color",
      },
    },
    id: "background",
    layoutGroups: [
      { columns: 2, controls: ["includeBackground", "background"], layout: "inline" },
    ],
    title: "Background",
  },
  {
    controls: {
      imageFormat: {
        applicability: always,
        defaultValue: "png",
        label: "Format",
        options: [
          { label: "PNG", value: "png" },
          { label: "JPG", value: "jpg" },
        ],
        performanceReason: "Format selects the runtime-owned image encoder.",
        performanceRole: "responsiveness",
        target: chromishTargets.imageFormat,
        type: "select",
      },
      imageResolution: {
        applicability: always,
        defaultValue: "4k",
        label: "Resolution",
        options: [
          { label: "2K", value: "2k" },
          { label: "4K", value: "4k" },
          { label: "8K", value: "8k" },
        ],
        performanceReason: "Resolution sets deterministic image-export pixel area.",
        performanceRole: "workload",
        target: chromishTargets.imageResolution,
        type: "select",
      },
    },
    id: "image-export",
    layoutGroups: [
      { columns: 2, controls: ["imageFormat", "imageResolution"], layout: "inline" },
    ],
    title: "Image Export",
  },
  {
    controls: {
      videoFormat: {
        applicability: always,
        defaultValue: "mp4",
        label: "Format",
        options: [
          { label: "MP4", value: "mp4" },
          { label: "WebM", value: "webm" },
        ],
        performanceReason: "Format selects the runtime-owned video encoder.",
        performanceRole: "responsiveness",
        target: chromishTargets.videoFormat,
        type: "select",
      },
      videoResolution: {
        applicability: always,
        defaultValue: "current",
        label: "Resolution",
        options: [
          { label: "Current", value: "current" },
          { label: "4K", value: "4k" },
        ],
        performanceReason: "Resolution sets deterministic 30 FPS video-export pixel area.",
        performanceRole: "workload",
        target: chromishTargets.videoResolution,
        type: "select",
      },
    },
    id: "video-export",
    layoutGroups: [
      { columns: 2, controls: ["videoFormat", "videoResolution"], layout: "inline" },
    ],
    title: "Video Export",
  },
  {
    actionGroup: "secondary",
    controls: {
      outputActions: {
        actions: [
          { icon: "download", label: "Download GLB Kit", role: "download-output", value: "download.glb-kit" },
          { icon: "download", label: "Download VGPU Kit", role: "download-output", value: "download.vgpu-kit" },
          { icon: "export", label: "Export PNG", role: "export-image", value: "export.image" },
          { icon: "export", label: "Export Video", role: "export-video", value: "export.video" },
        ],
        applicability: always,
        target: "actions.output",
        type: "panelActions",
      },
    },
    id: "delivery",
    title: "Export",
  },
] as const satisfies readonly ToolcraftControlSectionSchema[];
